# -*- coding: utf-8 -*-
"""July 1 Class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCW-_2ebg29MbtHhBS7y8lU5IE8y8Ory
"""

print("Welcome to the world of programming!")

print(4)

print("Hello Pythong \n")

print("hello",5)

print("welcome to ", end = "*")

x = 5
y = "John"
print(x)
print(y)

codingal = "codingal"
print(codingal)

name = input("enter your name: ")

print("\nHello", name, "welcome to codingal")

import keyword

print("Python keywords are...\n")
print(keyword.kwlist)